### ISSUE TITLE
add chat history

### ISSUE THREAD

**Issue by Conqxeror** [Conqxeror/contri-io#3]
### Task to be done related to chat history.

- [ ] a sidebar with the chat history needed.
- [ ] delete chat
- [ ] delete all chat
- [ ] set chat name

- ### open for contributions 🫡

**Comment by cpwallah** [comment]
hi i would like to work on this issue @Conqxeror

**Comment by Conqxeror** [comment]
@cpwallah Assigned to you, looking forward to your PR 🙌🏻!!

**Comment by cpwallah** [comment]
Thanks for opportunity bro will try my best @Conqxeror

**Comment by Conqxeror** [comment]
@cpwallah 🫡
